### ISSUE TITLE
Design SQL Schema for the opencocktail database

### ISSUE THREAD

**Issue by Chabare** [OpenAlcoholics/CockBot-OpenAPI#1]
1. Complete SQL Schema
2. Can be used by a migration service (e.g. [FlyWay](https://flywaydb.org/))

Possible tables:
1. drinks
2. ingredients
3. measurements
...

**Comment by BjoernPetersen** [comment]
Do we put the Schema here or into [CocktailParty](../../CocktailParty)?

**Comment by Chabare** [comment]
I'd say we treat the sql schemata the same as the openapi json/yaml files -> Put them here

The question is, do we
1. include this repo into all other repos as a submodule
2. sync it manually
3. include the other repos as a submodule

I think including the other repos here as a submodule is rather suboptimal...

**Comment by Chabare** [comment]
What infos do we need?

Cocktail: (maybe with history? (extra table))
- name (Gin Tonic)
- description (...)
- ingredients ("link" table)
- instructions (Put in ice cubes, gin, tonic, grapefruit and blueberry)
- category (g&t)
- image_link
- revision_date (24.08.2018)
- notes (the shit)

Ingredient:
- name (Brockmans Gin)
- measure (40%)
- image_link
- notes (Fruity)
- alcohol_percentage (40%)
- ingredient_category (Gin)

Categories:
- name (Highball)
- description (Contains some citrus variant)
- image_link

Ingredient Categories:
- name (Gin)
- alcoholic (true)
- is_accessory (false) (alternatively a Accessory category)
- image_link

Glasses:
- name (Copa Glass)
- size (200 ml)
- image_link

**Comment by BjoernPetersen** [comment]
I guess the best course of action would be including this repo as a submodule wherever it is needed.

As for the proposed schema:
## Accessories
I think accessories should be a separate table as they are somewhat optional and will have to be applied manually anyway.

## Instructions
Do we need written instructions? For the JSON schema I thought we provide an order for the ingredients and allow sublists to allow parallel pouring, roughly like this:

```
instructions: [
  ["tequila", "orange juice"], # can be poured simultaneously
  "grenadine syrup" # has to be poured afterwards
]
```

If we are going to do that, we need some notion of order in the database. I don't think written instructions are practical. For further manual instructions beyond pouring the drink ingredients (like accessory instructions), the `notes` column should suffice.

## Glasses
I think it's a good idea to suggest the type/form of glass typical for a cocktail. Glasses don't seem to be referenced outside the glasses table right now though (?).

I'm not sure how I feel about saving the glass volume in the database. It could be helpful to give an estimate for the typical glass of each form, but we shouldn't rely on that too heavily.

**Comment by Chabare** [comment]
I agree.

--- 

# Accessories
- name
- image_link
- notes
- before
- share 

How should we handle the share here? We could make it a varchar, percentage seems kinda weird.
We could also define it as `pieces` (integer) since most accessories are that way :thinking: (ice cubs, blueberries, mint leaves)

Should we have a `before` column, which defines whether to put the ingredient in before the rest (e.g. icecubes) or after (e.g. slice grapefruit on the rim)

---

# Glasses
I've added the relation drinks.glass -> glasses.id in 83a6eb447afc59f99b33a3584080628388d25f78.

yeah, we could rename it to `estimate_size` so people have an idea of the size, the frontend can handle how the user can choose the size of the drink though.

---

#Measure/share
As per @BjoernPetersen suggestion we remove `measure` from `drinks` and add it into the `drink_ingredients` table as `share` which has the same Constrains applied as now.

**Comment by FelixGail** [comment]
I think that depends upon whether cocktails without ice cubes exist. If not it is not necessary to handle ice cubes in our database model at all.

**Comment by BjoernPetersen** [comment]
My main concern is that the amount of ice depends not only on the glass volume, but also varies by glass and cocktail type.

**Comment by FelixGail** [comment]
In this case i would handle ice cubes as ingredient.

**Comment by Chabare** [comment]
I'd keep ice cubes inside the accessories table.

I don't really like the idea of assigning a `drink_ingredients.share` to ice cubes since that's usually arbitrary. Admittedly, pieces depends a lot on the size too, but I'd feel more comfortable with it.

It seems kinda weird to have ice cubes as an ingredient, I kinda feel that it's not all too different from a lime wedge in it's function in the cocktail. 

Let's think of the cockbot: We kinda imply that it manages everything in the ingredients table itself, whereas ice cubes have to be handled by the user. -> We'd have to mark it as an `accessory` or something in the like (`not_automatable`).

It'd kinda suck to make exceptions, especially if the ice cubes have some `drink_ingredients.rank` somewhere in the middle.

**Comment by BjoernPetersen** [comment]
How about we try to shoehorn ice cubes in neither `ingredients` nor `accessories`, but just add a `ice_cube_pcs` column to the `cocktails` table?

**Comment by Chabare** [comment]
### Ice cubes
1. We could make `ice_cubes` a boolean which just tells the user to add ice cubes. 
2. We could make a column `ice_cubes_share` which would be, how high you fill the glass with ice cubes.
3. Sure, we could do that, pieces is such a weird measure though... i don't think that anybody will actually count the pieces...
I've sorted this (^) list based on my preferences.

I'm against removing the ice cube information completely since there are some cocktails with ice and some without. 

### New
I've added a composite pk to drink_ingredients and drink_accessories (consisting of the two foreign keys).

**Comment by BjoernPetersen** [comment]
I was actually thinking we store the ice cubes in "pieces" but show them as some sort of share in the frontend. However, I reconsidered the whole thing and your `ice_cubes` boolean proposal is probably the best idea.

**Comment by Chabare** [comment]
Should we change [drinks.revision_date](https://github.com/OpenAlcoholics/CockBot-OpenAPI/blob/edcc9c1b7eeab32da7be01d63074d7dc51d8a2bd/sql/V1.4__Create_drinks.sql#L7) from type `date` to type `integer` and store a unix timestamp?

Are there any other changes we want to make to the current revision (edcc9c1)?

**Comment by BjoernPetersen** [comment]
We might as well, as I'm doing that conversion in the backend already.
